project_id = "hot.opensauced.pizza"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 14

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 7200
enable_signup = true

[auth.email]
enable_signup = false
double_confirm_changes = false
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "a8a233cae24bf1f6e786"
secret = "511e9cddd82699e3fecfc4dbec0f9fd25c719469"
